# Generated by Django 4.0.3 on 2022-04-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={},
        ),
        migrations.AlterField(
            model_name='book',
            name='Created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
